import type { Property } from './types'

export const demoProperties: Property[] = [
  {
    id: 'casa-cayala',
    title: 'Casa contemporánea cerca de Cayalá',
    description: 'Ambientes amplios, acabados cálidos y un jardín diseñado para disfrutar en familia. Ubicada en un sector residencial con seguridad y fácil acceso.',
    price: 485000,
    currency: 'USD',
    operation: 'Venta',
    type: 'Casa',
    city: 'Ciudad de Guatemala',
    zone: 'Zona 16',
    address: 'Sector residencial, Zona 16',
    bedrooms: 4,
    bathrooms: 4,
    parking: 3,
    area_m2: 380,
    status: 'Disponible',
    featured: true,
    published: true,
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=85'],
  },
  {
    id: 'apartamento-zona14',
    title: 'Apartamento con vistas en Zona 14',
    description: 'Apartamento iluminado con balcón, cocina abierta y amenidades completas. Una opción práctica para vivir cerca de restaurantes y servicios.',
    price: 2450,
    currency: 'USD',
    operation: 'Renta',
    type: 'Apartamento',
    city: 'Ciudad de Guatemala',
    zone: 'Zona 14',
    address: 'Avenida Las Américas, Zona 14',
    bedrooms: 3,
    bathrooms: 2,
    parking: 2,
    area_m2: 165,
    status: 'Disponible',
    featured: true,
    published: true,
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1400&q=85'],
  },
  {
    id: 'casa-antigua',
    title: 'Residencia con encanto en Antigua',
    description: 'Arquitectura inspirada en el estilo colonial, patio central y vistas a los volcanes. Ideal como residencia o inversión vacacional.',
    price: 620000,
    currency: 'USD',
    operation: 'Venta',
    type: 'Casa',
    city: 'Antigua Guatemala',
    zone: 'Sacatepéquez',
    address: 'Condominio privado, Antigua Guatemala',
    bedrooms: 5,
    bathrooms: 5,
    parking: 3,
    area_m2: 450,
    status: 'Disponible',
    featured: true,
    published: true,
    images: ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=85'],
  },
  {
    id: 'apartamento-zona10',
    title: 'Apartamento moderno en Zona 10',
    description: 'Diseño funcional, ventanales de piso a techo y ubicación estratégica en el corazón de la ciudad.',
    price: 198000,
    currency: 'USD',
    operation: 'Venta',
    type: 'Apartamento',
    city: 'Ciudad de Guatemala',
    zone: 'Zona 10',
    address: 'Zona Viva, Zona 10',
    bedrooms: 2,
    bathrooms: 2,
    parking: 2,
    area_m2: 112,
    status: 'Disponible',
    featured: false,
    published: true,
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=85'],
  },
]
